default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots_only do
    capture_screenshots(scheme: "BitBay-TickerUITests")
  end

  desc "Generate new localized screenshots and frame them"
  lane :screenshots_framed do
    capture_screenshots(scheme: "BitBay-TickerUITests")
    frame_screenshots
  end
end
