devices([
  "iPhone 8 Plus",
  "iPhone 11 Pro Max",
  "iPad Pro (12.9-inch) (3rd generation)",
  "iPad Pro (12.9-inch) (2nd generation)"
])

languages([
  "en-US"
])

clear_previous_screenshots(true)

launch_arguments(["-areFetchingRealTickers true"])
