name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: xcodebuild test -project Zonda-Tickers-iOS.xcodeproj -scheme Zonda\ Tickers -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0' -enableCodeCoverage YES
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
